runtime: php
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "8.3"
    document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    APP_NAME: "殘酷二選一"
    APP_ENV: production
    APP_KEY: base64:a+ZmB2k3KhJ8Xvb1UyyFuVFDadsYX77Phq5HEwegqMw=
    APP_DEBUG: true
    APP_URL: http://localhost
    ASSET_URL: http://localhost
    FORCE_HTTPS: false
    CONTAINER_NAME: 2pick.cc@gmail.com

    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: null
    LOG_LEVEL: debug

    DB_CONNECTION: mysql
    DB_HOST: two-pick-db
    DB_PORT: 3306
    DB_DATABASE: two-pick-db
    DB_USERNAME: root
    DB_PASSWORD: sbTMdklVEa)VLlLX

    BROADCAST_DRIVER: log
    CACHE_DRIVER: redis
    FILESYSTEM_DRIVER: s3
    QUEUE_CONNECTION: redis
    SESSION_DRIVER: redis
    SESSION_LIFETIME: 1440

    MEMCACHED_HOST: memcached

    REDIS_HOST: 127.0.0.1
    REDIS_PASSWORD: null
    REDIS_PORT: 6379

    MAIL_MAILER: smtp
    MAIL_HOST: mailhog
    MAIL_PORT: 1025
    MAIL_USERNAME: null
    MAIL_PASSWORD: null
    MAIL_ENCRYPTION: null
    MAIL_FROM_ADDRESS: null
    MAIL_FROM_NAME: "${APP_NAME}"

    # minio 
    AWS_ACCESS_KEY_ID: zrE1eF5BjvsDhljFQvs8
    AWS_SECRET_ACCESS_KEY: 7JFtpKaBFvGnF3NgaHpo4Gb6tnjBxi1XO7WytAlr
    AWS_DEFAULT_REGION: us-east-1
    AWS_BUCKET: test1
    AWS_URL: http://localhost:9000/test1
    AWS_ENDPOINT: http://ranking-web-minio-1:9000
    AWS_USE_PATH_STYLE_ENDPOINT: true

    GOOGLE_CLOUD_KEY_FILE: storage/rank-web-gcp.key
    GOOGLE_CLOUD_PROJECT_ID: rank-web
    GOOGLE_CLOUD_STORAGE_BUCKET: rank_test_bucket
    GOOGLE_CLOUD_STORAGE_PATH_PREFIX:
    GOOGLE_CLOUD_STORAGE_API_URI:
    GOOGLE_CLOUD_STORAGE_API_ENDPOINT:

    PUSHER_APP_ID:
    PUSHER_APP_KEY:
    PUSHER_APP_SECRET:
    PUSHER_APP_CLUSTER: mt1

    MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

    YOUTUBE_API_KEY: AIzaSyBRS7CoSljxPU72Owsg4ittca4pCtTWlw4

    TELESCOPE_ENABLED: false

    IMGUR_CLIENT_ID: da381352384f34f
    IMGUR_CLIENT_SECRET: 8c234452ee7cb2193a358d46370457ae071fe042
    IMGUR_ACCESS_TOKEN: 4e0c54e72eb731a6aa335dcbdb1ce3ef84a4e970
    IMGUR_REFRESH_TOEKN: 1c9f02a3a5b17915b2af6cad3547fa896e1387ea