runtime: php
env: flex

runtime_config: 
    operating_system: "ubuntu22"
    runtime_version: "8."
    document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100