#Deploy to App Engine
# steps:
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: [
#     '-c',
#     'gcloud config set app/cloud_build_timeout 3600 && gcloud app deploy -q --promote -v=$BUILD_ID --project=$PROJECT_ID'
#     ]
#   timeout: 3600s

#Deploy to Cloud Run
  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/two-pick-app:$COMMIT_SHA', '-f', 'gcloud/web/Dockerfile', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/two-pick-app:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'two-pick-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/two-pick-app:$COMMIT_SHA'
    - '--region'
    - '$LOCATION'
  images:
  - 'gcr.io/$PROJECT_ID/two-pick-app:$COMMIT_SHA'



# steps:
# - name: 'gcr.io/$PROJECT_ID/docker-compose'
#   args: ['up']
# tags: ['2pick-app-example']

# steps:
# - name: 'docker/compose:1.29.2'
#   args: ['up', '-d']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['tag', 'two-pick-app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
# images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
