<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'

import AdSlot from '../components/AdSlot.vue'
import { localizedPath, normalizeLocale, translate } from '../i18n'
import {
  carouselYoutubeEmbedURL,
  createPublicContentService,
  preferredElementImage,
  type CarouselItem,
  type Champion,
  type ChampionElement,
  type PostsPage,
  type Tag,
} from '../services/publicContent'

const route = useRoute()
const router = useRouter()
const locale = computed(() => normalizeLocale(route.params.locale))
const sort = computed<'hot' | 'new'>(() => route.path.endsWith('/new') ? 'new' : 'hot')
// Keep the public home-page query contract compatible with the original
// get-posts endpoint (`?k=...`). Accept `q` temporarily so links generated by
// the first separated-frontend build do not stop working.
const activeKeyword = computed(() => String(route.query.k || route.query.q || '').trim())
const service = createPublicContentService()
const defaultPreviewImage = '/image-placeholder.svg'

const postsPage = ref<PostsPage>({ items: [], page: 1, per_page: 15, total: 0, total_pages: 0 })
const tags = ref<Tag[]>([])
const carouselItems = ref<CarouselItem[]>([])
const champions = ref<Champion[]>([])
const loading = ref(true)
const refreshing = ref(false)
const loadingMore = ref(false)
const loadError = ref(false)
const loadMoreError = ref(false)
const activeCarouselIndex = ref(0)
const searchInput = ref(activeKeyword.value)
// One in-feed ad card per six vote cards.
const feedAdEvery = 6
let requestVersion = 0
let extrasRequestStarted = false
let lastLoadedRequestKey: string | null = null
let pendingResetRequestKey: string | null = null

const contentHeading = computed(() => activeKeyword.value
  ? `${translate(locale.value, 'searchResults')}「${activeKeyword.value}」`
  : translate(locale.value, sort.value === 'new' ? 'latestPicks' : 'popularPicks'))
const activeCarouselItem = computed(() => carouselItems.value[activeCarouselIndex.value] ?? null)
const hasMorePosts = computed(() => postsPage.value.page < postsPage.value.total_pages)

/**
 * The card indexes an in-feed ad follows.
 *
 * Every sixth card, except that AdSense allows neither ads on nor ads beside adult
 * content: a position whose card or following card is censored slides further down the
 * feed, and is dropped when the loaded feed runs out of clean neighbours.
 */
const feedAdPositions = computed<Set<number>>(() => {
  const items = postsPage.value.items
  const positions = new Set<number>()
  let anchor = feedAdEvery - 1
  while (anchor < items.length - 1) {
    let index = anchor
    const censored = (at: number): boolean => (items[at]?.is_censored ?? 0) > 0
    while (index < items.length - 1 && (censored(index) || censored(index + 1))) {
      index++
    }
    if (index >= items.length - 1) break
    positions.add(index)
    anchor = index + feedAdEvery
  }
  return positions
})

interface ChampionMarqueeItem extends Champion {
  winner: ChampionElement | null
  loser: ChampionElement | null
}

const championMarqueeItems = computed<ChampionMarqueeItem[]>(() => {
  const normalized = champions.value.map((champion) => {
    const candidates = [champion.left, champion.right].filter((candidate): candidate is ChampionElement => Boolean(candidate))
    return {
      ...champion,
      winner: candidates.find((candidate) => candidate.is_winner) ?? candidates[0] ?? null,
      loser: candidates.find((candidate) => !candidate.is_winner) ?? candidates[1] ?? null,
    }
  })
  return [...normalized, ...normalized]
})

watch([sort, activeKeyword, () => route.meta.viewKey], () => {
  if (route.meta.viewKey !== 'home') return
  searchInput.value = activeKeyword.value
  const nextRequestKey = `${sort.value}:${activeKeyword.value}`
  if (nextRequestKey === lastLoadedRequestKey) {
    if (pendingResetRequestKey && pendingResetRequestKey !== nextRequestKey) {
      requestVersion += 1
      pendingResetRequestKey = null
      loading.value = false
      refreshing.value = false
    }
    return
  }
  void loadPosts(true)
}, { immediate: true })
void loadHomeExtras()

async function loadPosts(reset: boolean): Promise<void> {
  const version = ++requestVersion
  const requestKey = `${sort.value}:${activeKeyword.value}`
  const refreshInPlace = reset && lastLoadedRequestKey !== null
  if (reset) {
    pendingResetRequestKey = requestKey
    loading.value = !refreshInPlace
    refreshing.value = refreshInPlace
    loadError.value = false
    loadMoreError.value = false
  } else {
    loadingMore.value = true
    loadMoreError.value = false
  }
  try {
    const result = await service.posts({
      sortBy: sort.value,
      range: 'week',
      keyword: activeKeyword.value,
      page: reset ? 1 : postsPage.value.page + 1,
    })
    if (version !== requestVersion) return
    if (reset) {
      postsPage.value = result
      lastLoadedRequestKey = requestKey
    } else {
      const existingSerials = new Set(postsPage.value.items.map((post) => post.serial))
      postsPage.value = {
        ...result,
        items: [...postsPage.value.items, ...result.items.filter((post) => !existingSerials.has(post.serial))],
      }
    }
  } catch {
    if (version === requestVersion) {
      if (reset) {
        if (!refreshInPlace) loadError.value = true
      } else {
        loadMoreError.value = true
      }
    }
  } finally {
    if (version === requestVersion) {
      if (reset) pendingResetRequestKey = null
      loading.value = false
      refreshing.value = false
      loadingMore.value = false
    }
  }
}

async function loadHomeExtras(): Promise<void> {
  if (extrasRequestStarted) return
  extrasRequestStarted = true
  const [tagsResult, carouselResult, championsResult] = await Promise.allSettled([
    service.hotTags(),
    service.carouselItems(),
    service.champions(),
  ])
  if (tagsResult.status === 'fulfilled') {
    tags.value = Object.entries(tagsResult.value)
      .map(([name, count]) => ({ name, count }))
      .sort((left, right) => right.count - left.count || left.name.localeCompare(right.name))
  }
  if (carouselResult.status === 'fulfilled') {
    carouselItems.value = carouselResult.value
    activeCarouselIndex.value = 0
  }
  if (championsResult.status === 'fulfilled') champions.value = championsResult.value
}

function submitSearch(): void {
  updateSearch(searchInput.value)
}

function selectTag(tag: string): void {
  searchInput.value = tag
  updateSearch(tag)
}

function clearSearch(): void {
  searchInput.value = ''
  updateSearch('')
}

function updateSearch(keyword: string): void {
  const query = { ...route.query }
  const normalized = keyword.trim().slice(0, 255)
  delete query.q
  if (normalized) query.k = normalized
  else delete query.k
  void router.push({ path: route.path, query })
}

function loadMorePosts(): void {
  if (!loadingMore.value && hasMorePosts.value) void loadPosts(false)
}

function gameURL(serial: string): string {
  return localizedPath(`/g/${encodeURIComponent(serial)}`, locale.value)
}

function rankURL(serial: string): string {
  return localizedPath(`/r/${encodeURIComponent(serial)}`, locale.value)
}

function browseURL(path: '/hot' | '/new'): string {
  const localized = localizedPath(path, locale.value)
  return activeKeyword.value
    ? `${localized}?${new URLSearchParams({ k: activeKeyword.value })}`
    : localized
}

function formatNumber(value: number): string {
  const language = locale.value === 'zh_TW' ? 'zh-TW' : locale.value
  return new Intl.NumberFormat(language, { notation: value >= 10_000 ? 'compact' : 'standard' }).format(value)
}

function isVideoThumbnail(url: string | null | undefined): boolean {
  return Boolean(url && /\.mp4(?:$|[?#])/i.test(url))
}

function voteCardImage(element: Parameters<typeof preferredElementImage>[0]): string {
  return preferredElementImage(element) || defaultPreviewImage
}

function useDefaultImage(event: Event): void {
  const image = event.currentTarget
  if (!(image instanceof HTMLImageElement) || image.dataset.fallbackApplied === 'true') return
  image.dataset.fallbackApplied = 'true'
  image.src = defaultPreviewImage
}

function showPreviousCarouselItem(): void {
  if (!carouselItems.value.length) return
  activeCarouselIndex.value = (activeCarouselIndex.value - 1 + carouselItems.value.length) % carouselItems.value.length
}

function showNextCarouselItem(): void {
  if (!carouselItems.value.length) return
  activeCarouselIndex.value = (activeCarouselIndex.value + 1) % carouselItems.value.length
}
</script>

<template>
  <div class="home-dashboard-layout">
    <aside class="home-discovery-rail">
      <section v-if="activeCarouselItem" class="highlight-section home-highlight-section">
    <div class="section-heading">
      <div>
        <p class="eyebrow">{{ translate(locale, 'highlightsEyebrow') }}</p>
        <h2>{{ translate(locale, 'communityHighlights') }}</h2>
      </div>
    </div>

    <div class="highlight-carousel-shell">
      <button
        v-if="carouselItems.length > 1"
        class="highlight-carousel-arrow is-previous"
        type="button"
        :aria-label="translate(locale, 'previousPage')"
        @click="showPreviousCarouselItem"
      >
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 5-7 7 7 7" /></svg>
      </button>
      <article :key="`${activeCarouselIndex}-${activeCarouselItem.video_id || activeCarouselItem.image_url}`" class="highlight-carousel-card">
        <div class="highlight-carousel-media">
          <iframe
            v-if="carouselYoutubeEmbedURL(activeCarouselItem)"
            :src="carouselYoutubeEmbedURL(activeCarouselItem) || ''"
            :title="activeCarouselItem.title || 'YouTube video'"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin"
            allowfullscreen
          />
          <a
            v-else-if="activeCarouselItem.image_url && activeCarouselItem.video_url"
            :href="activeCarouselItem.video_url"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img :src="activeCarouselItem.image_url" :alt="activeCarouselItem.title || ''">
          </a>
          <img
            v-else-if="activeCarouselItem.image_url"
            :src="activeCarouselItem.image_url"
            :alt="activeCarouselItem.title || ''"
          >
        </div>
        <div v-if="activeCarouselItem.title || activeCarouselItem.description" class="highlight-carousel-copy">
          <h3 v-if="activeCarouselItem.title">{{ activeCarouselItem.title }}</h3>
          <p v-if="activeCarouselItem.description && activeCarouselItem.description !== activeCarouselItem.title">
            {{ activeCarouselItem.description }}
          </p>
        </div>
      </article>
      <button
        v-if="carouselItems.length > 1"
        class="highlight-carousel-arrow is-next"
        type="button"
        :aria-label="translate(locale, 'nextPage')"
        @click="showNextCarouselItem"
      >
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7" /></svg>
      </button>
    </div>

    <div v-if="carouselItems.length > 1" class="highlight-carousel-position">
      <span>{{ activeCarouselIndex + 1 }} / {{ carouselItems.length }}</span>
      <div class="highlight-dots" role="group" :aria-label="translate(locale, 'communityHighlights')">
        <button
          v-for="(item, index) in carouselItems"
          :key="`${item.video_id || item.image_url}-${index}`"
          type="button"
          :class="{ active: activeCarouselIndex === index }"
          :aria-label="`${index + 1}: ${item.title || ''}`"
          :aria-current="activeCarouselIndex === index ? 'true' : undefined"
          @click="activeCarouselIndex = index"
        />
      </div>
    </div>
      </section>

      <AdSlot name="homeRail" shape="rectangle" :locale="locale" />

      <section v-if="champions.length" class="champion-marquee-section" :aria-label="translate(locale, 'recentChampions')">
    <div class="champion-marquee-heading">
      <p class="eyebrow">{{ translate(locale, 'justFinishedEyebrow') }}</p>
      <h2>{{ translate(locale, 'recentChampions') }}</h2>
    </div>
    <div class="champion-marquee-viewport">
      <div class="champion-marquee-track">
        <RouterLink
          v-for="(champion, index) in championMarqueeItems"
          :key="`${champion.key}-${index}`"
          :to="gameURL(champion.post_serial)"
          :aria-hidden="index >= champions.length ? 'true' : undefined"
          :tabindex="index >= champions.length ? -1 : undefined"
        >
          <small class="champion-marquee-title">{{ champion.post_title }}</small>
          <span class="champion-marquee-finalists">
            <span v-if="champion.winner" class="champion-marquee-candidate is-winner">
              <video
                v-if="isVideoThumbnail(champion.winner.thumb_url)"
                :src="`${champion.winner.thumb_url}#t=0.01`"
                muted
                playsinline
                preload="metadata"
              />
              <img v-else-if="champion.winner.thumb_url" :src="champion.winner.thumb_url" :alt="champion.winner.name" loading="lazy">
              <span><em>{{ translate(locale, 'championWinner') }}</em><strong>{{ champion.winner.name }}</strong></span>
            </span>
            <b aria-hidden="true">›</b>
            <span v-if="champion.loser" class="champion-marquee-candidate is-loser">
              <video
                v-if="isVideoThumbnail(champion.loser.thumb_url)"
                :src="`${champion.loser.thumb_url}#t=0.01`"
                muted
                playsinline
                preload="metadata"
              />
              <img v-else-if="champion.loser.thumb_url" :src="champion.loser.thumb_url" :alt="champion.loser.name" loading="lazy">
              <span><em>{{ translate(locale, 'championLoser') }}</em><strong>{{ champion.loser.name }}</strong></span>
            </span>
          </span>
        </RouterLink>
      </div>
    </div>
      </section>

      <AdSlot name="homeRailBottom" shape="vertical" :locale="locale" />
    </aside>

    <section
      class="public-content-section"
      :class="{ 'is-refreshing': refreshing }"
      :aria-busy="refreshing"
      aria-live="polite"
    >
    <div v-if="refreshing" class="home-refresh-progress" role="status">
      <span aria-hidden="true" />
      <span class="sr-only">{{ translate(locale, 'loadingVotes') }}</span>
    </div>
    <form class="vote-search" role="search" @submit.prevent="submitSearch">
      <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7" /><path d="m20 20-4-4" /></svg>
      <input
        v-model="searchInput"
        name="k"
        type="search"
        :placeholder="translate(locale, 'searchPlaceholder')"
        :aria-label="translate(locale, 'searchVotes')"
        maxlength="255"
      >
      <button v-if="activeKeyword" class="vote-search-clear" type="button" :aria-label="translate(locale, 'clearSearch')" @click="clearSearch">×</button>
      <button class="vote-search-submit" type="submit">{{ translate(locale, 'searchVotes') }}</button>
    </form>

    <div class="section-heading section-heading-inline">
      <div>
        <p class="eyebrow">{{ translate(locale, 'discoverEyebrow') }}</p>
        <!-- The page's only h1: this is what the home page is about. -->
        <h1>{{ contentHeading }}</h1>
      </div>
      <div class="content-tabs" :aria-label="translate(locale, 'browseVotes')">
        <RouterLink :class="{ active: sort === 'hot' }" :to="browseURL('/hot')">{{ translate(locale, 'popular') }}</RouterLink>
        <RouterLink :class="{ active: sort === 'new' }" :to="browseURL('/new')">{{ translate(locale, 'latest') }}</RouterLink>
      </div>
    </div>

    <div v-if="tags.length" class="tag-strip" :aria-label="translate(locale, 'hotTopics')">
      <span>{{ translate(locale, 'hotTopics') }}</span>
      <button
        v-for="tag in tags.slice(0, 9)"
        :key="tag.name"
        class="tag-chip"
        :class="{ active: activeKeyword.toLowerCase() === tag.name.toLowerCase() }"
        type="button"
        @click="selectTag(tag.name)"
      >#{{ tag.name }}</button>
    </div>

    <AdSlot name="homeTop" shape="horizontal" :locale="locale" />

    <div v-if="loading" class="content-state">
      <span class="loading-dot" aria-hidden="true" />
      {{ translate(locale, 'loadingVotes') }}
    </div>
    <div v-else-if="loadError" class="content-state content-state-error">
      <span>{{ translate(locale, 'loadVotesError') }}</span>
      <button type="button" @click="loadPosts(true)">{{ translate(locale, 'retry') }}</button>
    </div>
    <template v-else-if="postsPage.items.length">
      <div class="vote-grid">
        <template v-for="(post, index) in postsPage.items" :key="post.serial">
        <article class="vote-card">
        <RouterLink class="vote-card-main" :to="gameURL(post.serial)">
          <div class="vote-card-media" :class="{ 'is-censored': post.is_censored > 0 }">
            <div v-for="(element, side) in [post.element1, post.element2]" :key="side">
              <!-- The same file twice: blurred and cropped to fill the cell, then whole
                   and untouched on top. An option is often a portrait or a wide banner,
                   and cropping it to the cell is what used to cut heads and captions
                   off. Both tags carry one src, so the browser fetches it once. -->
              <img
                class="vote-card-media-backdrop"
                :src="voteCardImage(element)"
                alt=""
                aria-hidden="true"
                loading="lazy"
                decoding="async"
                @error="useDefaultImage"
              >
              <img
                class="vote-card-media-shot"
                :src="voteCardImage(element)"
                :alt="element.title || ''"
                loading="lazy"
                decoding="async"
                @error="useDefaultImage"
              >
              <span>{{ element.title }}</span>
            </div>
            <b aria-hidden="true">VS</b>
          </div>
          <div class="vote-card-copy">
            <h3>{{ post.title }}</h3>
            <div class="vote-card-meta">
              <span>{{ formatNumber(post.play_count) }} {{ translate(locale, 'plays') }}</span>
              <span>{{ formatNumber(post.elements_count) }} {{ translate(locale, 'options') }}</span>
            </div>
            <div v-if="post.tags.length" class="vote-card-tags">
              <span v-for="tag in post.tags.slice(0, 3)" :key="tag">#{{ tag }}</span>
            </div>
          </div>
        </RouterLink>
        <div class="vote-card-actions">
          <RouterLink class="vote-card-action-primary" :to="gameURL(post.serial)">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 5 11 7-11 7V5Z" /></svg>
            {{ translate(locale, 'openVote') }}
          </RouterLink>
          <RouterLink class="vote-card-action-quiet" :to="rankURL(post.serial)">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20v-7M10 20V8M16 20V4M22 20H2" /></svg>
            {{ translate(locale, 'viewRanking') }}
          </RouterLink>
        </div>
        </article>
        <AdSlot v-if="feedAdPositions.has(index)" name="homeFeed" shape="card" :locale="locale" />
        </template>
      </div>
      <div class="load-more-posts">
        <button v-if="hasMorePosts" type="button" :disabled="loadingMore" @click="loadMorePosts">
          {{ translate(locale, loadingMore ? 'loadingMore' : loadMoreError ? 'retry' : 'loadMore') }}
        </button>
      </div>
      <AdSlot name="homeFooter" shape="horizontal" :locale="locale" />
    </template>
    <div v-else class="content-state">{{ translate(locale, 'noVotes') }}</div>
    </section>
  </div>

</template>
